version: '3'
services:
    nginx:
        build:
            context: ./docker
            dockerfile: ./nginx.docker
        volumes:
            - ./:/var/www
            - ./docker/nginx/ssl:/etc/nginx/ssl
        ports:
            - "8075:80"
        links:
            - php-fpm
    php-fpm:
        build:
            context: ./docker
            dockerfile: ./php-fpm.docker
        volumes:
            - ./:/var/www
        links:
            - mysql
            - redis
            - elasticsearch
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=mysql"
            - "REDIS_PORT=6379"
            - "REDIS_HOST=redis"
            - "ELASTICSEARCH_HOSTS=elasticsearch:9200"
    php-cli:
        build:
            context: ./docker
            dockerfile: ./php-cli.docker
        volumes:
            - ./:/var/www
        links:
            - mysql
            - redis
            - elasticsearch
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=mysql"
            - "REDIS_PORT=6379"
            - "REDIS_HOST=redis"
            - "ELASTICSEARCH_HOSTS=elasticsearch:9200"
        tty: true
    mysql:
        image: mysql:5.7
        restart: always
        environment:
          - "MYSQL_ROOT_PASSWORD=secret"
          - "MYSQL_USER=app"
          - "MYSQL_PASSWORD=secret"
          - "MYSQL_DATABASE=app"
        ports:
            - 3306:3306
        volumes:
        - ./storage/docker/mysql:/var/lib/mysql
        expose:
            - 3306
    redis:
        image: redis:3.0
        ports:
            - "63791:6379"
    node:
        image: node:18.12.0-alpine
        volumes:
            - ./:/var/www
        working_dir: /var/www
        ports:
          - 5173:5173
        tty: true
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
        environment:
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - ./storage/docker/elasticsearch:/usr/share/elasticsearch/data
        ports:
            - "9201:9200"
    adminer:
      image: adminer
      restart: always
      ports:
        - 8076:8080
    rabbitmq:
      image: rabbitmq:3.10.7-management
      hostname: rabbitmq
      ports:
        - 15672:15672
        - 5672:5672
      volumes:
        - ./rabbitmq:/var/lib/rabbitmq
      restart: always
      environment:
        - RABBITMQ_DEFAULT_USER=rmuser  
        - RABBITMQ_DEFAULT_PASS=rmpassword
        - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648
      command: ["bash", "-c", "chmod 400 /var/lib/rabbitmq/.erlang.cookie; rabbitmq-server"]